/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_UserProfileI (void);
GtkWidget* create_SignUpI (void);
GtkWidget* create_signInI (void);
GtkWidget* create_deleteAlert (void);
GtkWidget* create_updateAlertI (void);
GtkWidget* create_adminCitoyen (void);
GtkWidget* create_sendEmail (void);
GtkWidget* create_adminDashboardI (void);
GtkWidget* create_citoyenDashboardI (void);
GtkWidget* create_Layout (void);
GtkWidget* create_Supp (void);
GtkWidget* create_ADD_MOD (void);
GtkWidget* create_Affich (void);
GtkWidget* create_Affec_agent (void);
GtkWidget* create_CONFIR_supp (void);
GtkWidget* create_itafwinaffichage (void);
GtkWidget* create_itafwinajouter (void);
GtkWidget* create_itafwinmodifier (void);
GtkWidget* create_itafwinsupprimer (void);
GtkWidget* create_itafwinrechercherparplace (void);
GtkWidget* create_itafwineffichagetouteslesreser (void);
GtkWidget* create_itafwinremerciment (void);
GtkWidget* create_main_window_ww (void);
GtkWidget* create_window_ajouter_ww (void);
GtkWidget* create_window_modifier_ww (void);
GtkWidget* create_window_supprimer_ww (void);
GtkWidget* create_window_afficher_ww (void);
GtkWidget* create_window_affecter_ww (void);
GtkWidget* create_Ajouter_un_agent (void);
GtkWidget* create_connexion_admin (void);
GtkWidget* create_Erreur_de_connexion_admin (void);
GtkWidget* create_Supprimer_un_agent (void);
GtkWidget* create_agent_introuvable (void);
GtkWidget* create_mis____jour_compte_agent (void);
GtkWidget* create_labelprincipale (void);
GtkWidget* create___tes_vous_sur_de_vouloir__supprimer_l_agent_de_la_liste___ (void);
GtkWidget* create_mot_de_passe_incorrecte (void);
GtkWidget* create_demande_mdp (void);
GtkWidget* create_demande_modifier_cin_agent (void);
GtkWidget* create_date_de_r__servation (void);
GtkWidget* create_pas_de_r__servation (void);
GtkWidget* create_liste_des_r__servations (void);
GtkWidget* create___tes_vous_sur_de_vouloir_modifier_les_information_de_l_agent (void);
GtkWidget* create_Veuillez_remplir_tous_les_champs (void);
