/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Layout (void)
{
  GtkWidget *Layout;
  GtkWidget *fixed2;
  GtkWidget *ED_image2_gestionparking;
  GtkWidget *ED_image4_gestionparking;
  GtkWidget *ED_image3_gestionparking;
  GtkWidget *ED_image5_gestionparking;
  GtkWidget *ED_image10_gestionparking;
  GtkWidget *ED_button6_gestionparking;
  GtkWidget *ED_button4_gestionparking;
  GtkWidget *ED_button10_gestionparking;
  GtkWidget *ED_button3_gestionparking;
  GtkWidget *ED_button1_gestionparking;
  GtkWidget *ED_button5_gestionparking;
  GtkWidget *ED_image6_gestionparking;

  Layout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Layout), _("Layout"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Layout), fixed2);

  ED_image2_gestionparking = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (ED_image2_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed2), ED_image2_gestionparking, 32, 56);
  gtk_widget_set_size_request (ED_image2_gestionparking, 40, 32);

  ED_image4_gestionparking = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (ED_image4_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed2), ED_image4_gestionparking, 40, 112);
  gtk_widget_set_size_request (ED_image4_gestionparking, 21, 21);

  ED_image3_gestionparking = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (ED_image3_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed2), ED_image3_gestionparking, 40, 152);
  gtk_widget_set_size_request (ED_image3_gestionparking, 29, 32);

  ED_image5_gestionparking = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (ED_image5_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed2), ED_image5_gestionparking, 40, 240);
  gtk_widget_set_size_request (ED_image5_gestionparking, 32, 32);

  ED_image10_gestionparking = gtk_image_new_from_stock ("gtk-quit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (ED_image10_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed2), ED_image10_gestionparking, 48, 296);
  gtk_widget_set_size_request (ED_image10_gestionparking, 21, 21);

  ED_button6_gestionparking = gtk_button_new_with_mnemonic (_("Affectation des agents"));
  gtk_widget_show (ED_button6_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed2), ED_button6_gestionparking, 72, 200);
  gtk_widget_set_size_request (ED_button6_gestionparking, 200, 32);

  ED_button4_gestionparking = gtk_button_new_with_mnemonic (_("Modification du parking"));
  gtk_widget_show (ED_button4_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed2), ED_button4_gestionparking, 72, 104);
  gtk_widget_set_size_request (ED_button4_gestionparking, 200, 32);

  ED_button10_gestionparking = gtk_button_new_with_mnemonic (_("Affichage "));
  gtk_widget_show (ED_button10_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed2), ED_button10_gestionparking, 72, 240);
  gtk_widget_set_size_request (ED_button10_gestionparking, 200, 32);

  ED_button3_gestionparking = gtk_button_new_with_mnemonic (_("Ajout du parking"));
  gtk_widget_show (ED_button3_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed2), ED_button3_gestionparking, 72, 56);
  gtk_widget_set_size_request (ED_button3_gestionparking, 200, 32);

  ED_button1_gestionparking = gtk_button_new_with_mnemonic (_("Quitter"));
  gtk_widget_show (ED_button1_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed2), ED_button1_gestionparking, 80, 288);
  gtk_widget_set_size_request (ED_button1_gestionparking, 192, 32);

  ED_button5_gestionparking = gtk_button_new_with_mnemonic (_("Suppression du parking"));
  gtk_widget_show (ED_button5_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed2), ED_button5_gestionparking, 72, 152);
  gtk_widget_set_size_request (ED_button5_gestionparking, 200, 32);

  ED_image6_gestionparking = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (ED_image6_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed2), ED_image6_gestionparking, 48, 208);
  gtk_widget_set_size_request (ED_image6_gestionparking, 21, 21);

  g_signal_connect ((gpointer) ED_button6_gestionparking, "clicked",
                    G_CALLBACK (on_ED_button6_gestionparking_clicked),
                    NULL);
  g_signal_connect ((gpointer) ED_button4_gestionparking, "clicked",
                    G_CALLBACK (on_ED_button4_gestionparking_clicked),
                    NULL);
  g_signal_connect ((gpointer) ED_button10_gestionparking, "clicked",
                    G_CALLBACK (on_ED_button10_gestionparking_clicked),
                    NULL);
  g_signal_connect ((gpointer) ED_button3_gestionparking, "clicked",
                    G_CALLBACK (on_ED_button3_gestionparking_clicked),
                    NULL);
  g_signal_connect ((gpointer) ED_button1_gestionparking, "clicked",
                    G_CALLBACK (on_ED_button1_gestionparking_clicked),
                    NULL);
  g_signal_connect ((gpointer) ED_button5_gestionparking, "clicked",
                    G_CALLBACK (on_ED_button5_gestionparking_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Layout, Layout, "Layout");
  GLADE_HOOKUP_OBJECT (Layout, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Layout, ED_image2_gestionparking, "ED_image2_gestionparking");
  GLADE_HOOKUP_OBJECT (Layout, ED_image4_gestionparking, "ED_image4_gestionparking");
  GLADE_HOOKUP_OBJECT (Layout, ED_image3_gestionparking, "ED_image3_gestionparking");
  GLADE_HOOKUP_OBJECT (Layout, ED_image5_gestionparking, "ED_image5_gestionparking");
  GLADE_HOOKUP_OBJECT (Layout, ED_image10_gestionparking, "ED_image10_gestionparking");
  GLADE_HOOKUP_OBJECT (Layout, ED_button6_gestionparking, "ED_button6_gestionparking");
  GLADE_HOOKUP_OBJECT (Layout, ED_button4_gestionparking, "ED_button4_gestionparking");
  GLADE_HOOKUP_OBJECT (Layout, ED_button10_gestionparking, "ED_button10_gestionparking");
  GLADE_HOOKUP_OBJECT (Layout, ED_button3_gestionparking, "ED_button3_gestionparking");
  GLADE_HOOKUP_OBJECT (Layout, ED_button1_gestionparking, "ED_button1_gestionparking");
  GLADE_HOOKUP_OBJECT (Layout, ED_button5_gestionparking, "ED_button5_gestionparking");
  GLADE_HOOKUP_OBJECT (Layout, ED_image6_gestionparking, "ED_image6_gestionparking");

  return Layout;
}

GtkWidget*
create_Supp (void)
{
  GtkWidget *Supp;
  GtkWidget *fixed3;
  GtkWidget *ED_entry33_gestionparking;
  GtkWidget *ED_label9_gestionparking;
  GtkWidget *ED_label8_gestionparking;
  GtkWidget *ED_treeview1_gestionparking;
  GtkWidget *ED_button8_gestionparking;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image12;
  GtkWidget *label26;
  GtkWidget *ED_button9_gestionparking;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image13;
  GtkWidget *label27;
  GtkWidget *Actualiser;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image14;
  GtkWidget *label28;

  Supp = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Supp), _("Suppression"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Supp), fixed3);

  ED_entry33_gestionparking = gtk_entry_new ();
  gtk_widget_show (ED_entry33_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed3), ED_entry33_gestionparking, 176, 56);
  gtk_widget_set_size_request (ED_entry33_gestionparking, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ED_entry33_gestionparking), 8226);

  ED_label9_gestionparking = gtk_label_new (_("Parking ID :"));
  gtk_widget_show (ED_label9_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed3), ED_label9_gestionparking, 8, 40);
  gtk_widget_set_size_request (ED_label9_gestionparking, 136, 40);
  gtk_misc_set_alignment (GTK_MISC (ED_label9_gestionparking), 1, 1);

  ED_label8_gestionparking = gtk_label_new (_("Delete"));
  gtk_widget_show (ED_label8_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed3), ED_label8_gestionparking, 64, 8);
  gtk_widget_set_size_request (ED_label8_gestionparking, 256, 24);

  ED_treeview1_gestionparking = gtk_tree_view_new ();
  gtk_widget_show (ED_treeview1_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed3), ED_treeview1_gestionparking, 72, 104);
  gtk_widget_set_size_request (ED_treeview1_gestionparking, 552, 296);

  ED_button8_gestionparking = gtk_button_new ();
  gtk_widget_show (ED_button8_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed3), ED_button8_gestionparking, 80, 424);
  gtk_widget_set_size_request (ED_button8_gestionparking, 144, 48);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (ED_button8_gestionparking), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image12 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox11), image12, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Delete"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox11), label26, FALSE, FALSE, 0);

  ED_button9_gestionparking = gtk_button_new ();
  gtk_widget_show (ED_button9_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed3), ED_button9_gestionparking, 232, 424);
  gtk_widget_set_size_request (ED_button9_gestionparking, 144, 48);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (ED_button9_gestionparking), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image13 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox12), image13, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Cancel"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox12), label27, FALSE, FALSE, 0);

  Actualiser = gtk_button_new ();
  gtk_widget_show (Actualiser);
  gtk_fixed_put (GTK_FIXED (fixed3), Actualiser, 384, 424);
  gtk_widget_set_size_request (Actualiser, 144, 48);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (Actualiser), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image14 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox13), image14, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Actualiser"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox13), label28, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) ED_entry33_gestionparking, "changed",
                    G_CALLBACK (on_ED_entry33_gestionparking_changed),
                    NULL);
  g_signal_connect ((gpointer) ED_treeview1_gestionparking, "row_activated",
                    G_CALLBACK (on_ED_treeview1_gestionparking_row_activated),
                    NULL);
  g_signal_connect ((gpointer) ED_button8_gestionparking, "clicked",
                    G_CALLBACK (on_ED_button8_gestionparking_clicked),
                    NULL);
  g_signal_connect ((gpointer) ED_button9_gestionparking, "clicked",
                    G_CALLBACK (on_ED_button9_gestionparking_clicked),
                    NULL);
  g_signal_connect ((gpointer) Actualiser, "clicked",
                    G_CALLBACK (on_Actualiser_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Supp, Supp, "Supp");
  GLADE_HOOKUP_OBJECT (Supp, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Supp, ED_entry33_gestionparking, "ED_entry33_gestionparking");
  GLADE_HOOKUP_OBJECT (Supp, ED_label9_gestionparking, "ED_label9_gestionparking");
  GLADE_HOOKUP_OBJECT (Supp, ED_label8_gestionparking, "ED_label8_gestionparking");
  GLADE_HOOKUP_OBJECT (Supp, ED_treeview1_gestionparking, "ED_treeview1_gestionparking");
  GLADE_HOOKUP_OBJECT (Supp, ED_button8_gestionparking, "ED_button8_gestionparking");
  GLADE_HOOKUP_OBJECT (Supp, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Supp, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Supp, image12, "image12");
  GLADE_HOOKUP_OBJECT (Supp, label26, "label26");
  GLADE_HOOKUP_OBJECT (Supp, ED_button9_gestionparking, "ED_button9_gestionparking");
  GLADE_HOOKUP_OBJECT (Supp, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Supp, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Supp, image13, "image13");
  GLADE_HOOKUP_OBJECT (Supp, label27, "label27");
  GLADE_HOOKUP_OBJECT (Supp, Actualiser, "Actualiser");
  GLADE_HOOKUP_OBJECT (Supp, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Supp, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Supp, image14, "image14");
  GLADE_HOOKUP_OBJECT (Supp, label28, "label28");

  return Supp;
}

GtkWidget*
create_ADD_MOD (void)
{
  GtkWidget *ADD_MOD;
  GtkWidget *fixed4;
  GtkObject *ED_spinbutton4_gestionparking_adj;
  GtkWidget *ED_spinbutton4_gestionparking;
  GtkWidget *ED_entry4_gestionparking;
  GtkObject *ED_spinbutton1_gestionparking_adj;
  GtkWidget *ED_spinbutton1_gestionparking;
  GtkWidget *ED_label13_gestionparking;
  GtkWidget *ED_label14_gestionparking;
  GtkWidget *ED_radiobutton2_gestionparking;
  GSList *ED_radiobutton2_gestionparking_group = NULL;
  GtkWidget *ED_radiobutton1_gestionparking;
  GtkWidget *ED_label11_gestionparking;
  GtkWidget *ED_label15_gestionparking;
  GtkWidget *ED_label10_gestionparking;
  GtkWidget *ED_label20_gestionparking;
  GtkWidget *ED_label16_gestionparking;
  GtkWidget *ED_label26_gestionparking;
  
  GtkWidget *ED_checkbutton2_gestionparking;
  GtkWidget *ED_checkbutton3_gestionparking;
  GtkWidget *ED_checkbutton1_gestionparking;
  GtkWidget *ED_button13_gestionparking;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label12;
  GtkWidget *ED_button111_gestionparking;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image6;
  GtkWidget *label15;
  GtkWidget *ED_button14_gestionparking;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label13;
  GtkWidget *label_message;
  GtkWidget *Rech;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image16;
  GtkWidget *label30;
  GtkWidget *ED_comboboxentry1_gestionparking;
  GtkWidget *ED_comboboxentry2_gestionparking;

  ADD_MOD = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ADD_MOD), _("Addition+modification"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (ADD_MOD), fixed4);

  ED_spinbutton4_gestionparking_adj = gtk_adjustment_new (1, 0, 1000, 1, 10, 10);
  ED_spinbutton4_gestionparking = gtk_spin_button_new (GTK_ADJUSTMENT (ED_spinbutton4_gestionparking_adj), 1, 0);
  gtk_widget_show (ED_spinbutton4_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed4), ED_spinbutton4_gestionparking, 176, 208);
  gtk_widget_set_size_request (ED_spinbutton4_gestionparking, 60, 27);

  ED_entry4_gestionparking = gtk_entry_new ();
  gtk_widget_show (ED_entry4_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed4), ED_entry4_gestionparking, 144, 56);
  gtk_widget_set_size_request (ED_entry4_gestionparking, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ED_entry4_gestionparking), 8226);

  ED_spinbutton1_gestionparking_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  ED_spinbutton1_gestionparking = gtk_spin_button_new (GTK_ADJUSTMENT (ED_spinbutton1_gestionparking_adj), 1, 0);
  gtk_widget_show (ED_spinbutton1_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed4), ED_spinbutton1_gestionparking, 112, 248);
  gtk_widget_set_size_request (ED_spinbutton1_gestionparking, 60, 27);

  ED_label13_gestionparking = gtk_label_new (_("Addition +modification"));
  gtk_widget_show (ED_label13_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed4), ED_label13_gestionparking, 80, 8);
  gtk_widget_set_size_request (ED_label13_gestionparking, 240, 40);

  ED_label14_gestionparking = gtk_label_new (_("Parking ID :"));
  gtk_widget_show (ED_label14_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed4), ED_label14_gestionparking, 16, 56);
  gtk_widget_set_size_request (ED_label14_gestionparking, 152, 24);

  ED_radiobutton2_gestionparking = gtk_radio_button_new_with_mnemonic (NULL, _("plain air"));
  gtk_widget_show (ED_radiobutton2_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed4), ED_radiobutton2_gestionparking, 192, 344);
  gtk_widget_set_size_request (ED_radiobutton2_gestionparking, 116, 24);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ED_radiobutton2_gestionparking), ED_radiobutton2_gestionparking_group);
  ED_radiobutton2_gestionparking_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ED_radiobutton2_gestionparking));

  ED_radiobutton1_gestionparking = gtk_radio_button_new_with_mnemonic (NULL, _("Couvert"));
  gtk_widget_show (ED_radiobutton1_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed4), ED_radiobutton1_gestionparking, 304, 336);
  gtk_widget_set_size_request (ED_radiobutton1_gestionparking, 104, 40);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (ED_radiobutton1_gestionparking), ED_radiobutton2_gestionparking_group);
  ED_radiobutton2_gestionparking_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (ED_radiobutton1_gestionparking));

  ED_label11_gestionparking = gtk_label_new (_("Type parking :"));
  gtk_widget_show (ED_label11_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed4), ED_label11_gestionparking, 0, 296);
  gtk_widget_set_size_request (ED_label11_gestionparking, 160, 40);

  ED_label15_gestionparking = gtk_label_new (_("Localisation :"));
  gtk_widget_show (ED_label15_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed4), ED_label15_gestionparking, 0, 136);
  gtk_widget_set_size_request (ED_label15_gestionparking, 136, 24);

  ED_label10_gestionparking = gtk_label_new (_("Prix :"));
  gtk_widget_show (ED_label10_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed4), ED_label10_gestionparking, 16, 240);
  gtk_widget_set_size_request (ED_label10_gestionparking, 80, 40);

  ED_label20_gestionparking = gtk_label_new (_("Parking ID :"));
  gtk_widget_show (ED_label20_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed4), ED_label20_gestionparking, 16, 56);
  gtk_widget_set_size_request (ED_label20_gestionparking, 152, 24);

  ED_label16_gestionparking = gtk_label_new (_("nombre de place :"));
  gtk_widget_show (ED_label16_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed4), ED_label16_gestionparking, 0, 216);
  gtk_widget_set_size_request (ED_label16_gestionparking, 160, 16);

  ED_label26_gestionparking = gtk_label_new (_("Couverture parking :"));
  gtk_widget_show (ED_label26_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed4), ED_label26_gestionparking, 16, 344);
  gtk_widget_set_size_request (ED_label26_gestionparking, 160, 24);

  ED_label14_gestionparking = gtk_label_new (_("Horraire :"));
  gtk_widget_show (ED_label14_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed4), ED_label14_gestionparking, 16, 432);
  gtk_widget_set_size_request (ED_label14_gestionparking, 72, 16);

  ED_checkbutton2_gestionparking = gtk_check_button_new_with_mnemonic (_("Parking public"));
  gtk_widget_show (ED_checkbutton2_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed4), ED_checkbutton2_gestionparking, 184, 304);
  gtk_widget_set_size_request (ED_checkbutton2_gestionparking, 136, 24);

  ED_checkbutton3_gestionparking = gtk_check_button_new_with_mnemonic (_("Sous-sol"));
  gtk_widget_show (ED_checkbutton3_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed4), ED_checkbutton3_gestionparking, 472, 304);
  gtk_widget_set_size_request (ED_checkbutton3_gestionparking, 118, 24);

  ED_checkbutton1_gestionparking = gtk_check_button_new_with_mnemonic (_("Parking priv\303\251"));
  gtk_widget_show (ED_checkbutton1_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed4), ED_checkbutton1_gestionparking, 320, 304);
  gtk_widget_set_size_request (ED_checkbutton1_gestionparking, 152, 24);

  ED_button13_gestionparking = gtk_button_new ();
  gtk_widget_show (ED_button13_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed4), ED_button13_gestionparking, 120, 600);
  gtk_widget_set_size_request (ED_button13_gestionparking, 74, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (ED_button13_gestionparking), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Add"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox3), label12, FALSE, FALSE, 0);

  ED_button111_gestionparking = gtk_button_new ();
  gtk_widget_show (ED_button111_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed4), ED_button111_gestionparking, 208, 600);
  gtk_widget_set_size_request (ED_button111_gestionparking, 72, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (ED_button111_gestionparking), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image6 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox5), image6, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Mod"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox5), label15, FALSE, FALSE, 0);

  ED_button14_gestionparking = gtk_button_new ();
  gtk_widget_show (ED_button14_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed4), ED_button14_gestionparking, 288, 600);
  gtk_widget_set_size_request (ED_button14_gestionparking, 80, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (ED_button14_gestionparking), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Cancel"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox4), label13, FALSE, FALSE, 0);

  label_message = gtk_label_new ("");
  gtk_widget_show (label_message);
  gtk_fixed_put (GTK_FIXED (fixed4), label_message, 8, 464);
  gtk_widget_set_size_request (label_message, 608, 120);

  Rech = gtk_button_new ();
  gtk_widget_show (Rech);
  gtk_fixed_put (GTK_FIXED (fixed4), Rech, 328, 88);
  gtk_widget_set_size_request (Rech, 128, 40);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (Rech), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image16 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox15), image16, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox15), label30, FALSE, FALSE, 0);

  ED_comboboxentry1_gestionparking = gtk_combo_box_entry_new_text ();
  gtk_widget_show (ED_comboboxentry1_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed4), ED_comboboxentry1_gestionparking, 136, 136);
  gtk_widget_set_size_request (ED_comboboxentry1_gestionparking, 189, 29);
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry1_gestionparking), _("Ben Arous"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry1_gestionparking), _("Ariana "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry1_gestionparking), _("MAnouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry1_gestionparking), _("Bizerte "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry1_gestionparking), _("Zaghouan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry1_gestionparking), _("Nabeul"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry1_gestionparking), _("Jendouba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry1_gestionparking), _("B\303\251j\303\240"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry1_gestionparking), _("EL Kef "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry1_gestionparking), _("Siliana"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry1_gestionparking), _("Sousse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry1_gestionparking), _("Monastir "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry1_gestionparking), _("Mahdia"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry1_gestionparking), _("Kairaouan"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry1_gestionparking), _("Kasserine  "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry1_gestionparking), _("Sidi Bouzid"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry1_gestionparking), _("Sfax"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry1_gestionparking), _("Gab\303\251s"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry1_gestionparking), _("Mednine "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry1_gestionparking), _("Tataouine"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry1_gestionparking), _("Gafsa"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry1_gestionparking), _("Tozeur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry1_gestionparking), _("K\303\251billi"));

  ED_comboboxentry2_gestionparking = gtk_combo_box_entry_new_text ();
  gtk_widget_show (ED_comboboxentry2_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed4), ED_comboboxentry2_gestionparking, 112, 424);
  gtk_widget_set_size_request (ED_comboboxentry2_gestionparking, 152, 24);
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry2_gestionparking), _("00:00-08:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry2_gestionparking), _("06:00-12:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry2_gestionparking), _("12:00-17:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry2_gestionparking), _("12:00-00:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry2_gestionparking), _("10:00-20:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry2_gestionparking), _("18:00-08:00"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (ED_comboboxentry2_gestionparking), _("12:00-22:00"));

  g_signal_connect ((gpointer) ED_button13_gestionparking, "clicked",
                    G_CALLBACK (on_ED_button13_gestionparking_clicked),
                    NULL);
  g_signal_connect ((gpointer) ED_button111_gestionparking, "clicked",
                    G_CALLBACK (on_ED_button111_gestionparking_clicked),
                    NULL);
  g_signal_connect ((gpointer) ED_button14_gestionparking, "clicked",
                    G_CALLBACK (on_ED_button14_gestionparking_clicked),
                    NULL);
  g_signal_connect ((gpointer) Rech, "clicked",
                    G_CALLBACK (on_Rech_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ADD_MOD, ADD_MOD, "ADD_MOD");
  GLADE_HOOKUP_OBJECT (ADD_MOD, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (ADD_MOD, ED_spinbutton4_gestionparking, "ED_spinbutton4_gestionparking");
  GLADE_HOOKUP_OBJECT (ADD_MOD, ED_entry4_gestionparking, "ED_entry4_gestionparking");
  GLADE_HOOKUP_OBJECT (ADD_MOD, ED_spinbutton1_gestionparking, "ED_spinbutton1_gestionparking");
  GLADE_HOOKUP_OBJECT (ADD_MOD, ED_label13_gestionparking, "ED_label13_gestionparking");
  GLADE_HOOKUP_OBJECT (ADD_MOD, ED_label14_gestionparking, "ED_label14_gestionparking");
  GLADE_HOOKUP_OBJECT (ADD_MOD, ED_radiobutton2_gestionparking, "ED_radiobutton2_gestionparking");
  GLADE_HOOKUP_OBJECT (ADD_MOD, ED_radiobutton1_gestionparking, "ED_radiobutton1_gestionparking");
  GLADE_HOOKUP_OBJECT (ADD_MOD, ED_label11_gestionparking, "ED_label11_gestionparking");
  GLADE_HOOKUP_OBJECT (ADD_MOD, ED_label15_gestionparking, "ED_label15_gestionparking");
  GLADE_HOOKUP_OBJECT (ADD_MOD, ED_label10_gestionparking, "ED_label10_gestionparking");
  GLADE_HOOKUP_OBJECT (ADD_MOD, ED_label20_gestionparking, "ED_label20_gestionparking");
  GLADE_HOOKUP_OBJECT (ADD_MOD, ED_label16_gestionparking, "ED_label16_gestionparking");
  GLADE_HOOKUP_OBJECT (ADD_MOD, ED_label26_gestionparking, "ED_label26_gestionparking");
  GLADE_HOOKUP_OBJECT (ADD_MOD, ED_label14_gestionparking, "ED_label14_gestionparking");
  GLADE_HOOKUP_OBJECT (ADD_MOD, ED_checkbutton2_gestionparking, "ED_checkbutton2_gestionparking");
  GLADE_HOOKUP_OBJECT (ADD_MOD, ED_checkbutton3_gestionparking, "ED_checkbutton3_gestionparking");
  GLADE_HOOKUP_OBJECT (ADD_MOD, ED_checkbutton1_gestionparking, "ED_checkbutton1_gestionparking");
  GLADE_HOOKUP_OBJECT (ADD_MOD, ED_button13_gestionparking, "ED_button13_gestionparking");
  GLADE_HOOKUP_OBJECT (ADD_MOD, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (ADD_MOD, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (ADD_MOD, image4, "image4");
  GLADE_HOOKUP_OBJECT (ADD_MOD, label12, "label12");
  GLADE_HOOKUP_OBJECT (ADD_MOD, ED_button111_gestionparking, "ED_button111_gestionparking");
  GLADE_HOOKUP_OBJECT (ADD_MOD, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (ADD_MOD, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (ADD_MOD, image6, "image6");
  GLADE_HOOKUP_OBJECT (ADD_MOD, label15, "label15");
  GLADE_HOOKUP_OBJECT (ADD_MOD, ED_button14_gestionparking, "ED_button14_gestionparking");
  GLADE_HOOKUP_OBJECT (ADD_MOD, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (ADD_MOD, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (ADD_MOD, image5, "image5");
  GLADE_HOOKUP_OBJECT (ADD_MOD, label13, "label13");
  GLADE_HOOKUP_OBJECT (ADD_MOD, label_message, "label_message");
  GLADE_HOOKUP_OBJECT (ADD_MOD, Rech, "Rech");
  GLADE_HOOKUP_OBJECT (ADD_MOD, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (ADD_MOD, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (ADD_MOD, image16, "image16");
  GLADE_HOOKUP_OBJECT (ADD_MOD, label30, "label30");
  GLADE_HOOKUP_OBJECT (ADD_MOD, ED_comboboxentry1_gestionparking, "ED_comboboxentry1_gestionparking");
  GLADE_HOOKUP_OBJECT (ADD_MOD, ED_comboboxentry2_gestionparking, "ED_comboboxentry2_gestionparking");

  return ADD_MOD;
}

GtkWidget*
create_Affich (void)
{
  GtkWidget *Affich;
  GtkWidget *fixed5;
  GtkWidget *ED_treeview11_gestionparking;
  GtkWidget *ED_label19_gestionparking;
  GtkWidget *ED_label22_gestionparking;
  GtkWidget *ED_entry2_AFFgestionparking;
  GtkWidget *ED_button2_gestionparking;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image11;
  GtkWidget *label25;

  Affich = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Affich), _("Affichage"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Affich), fixed5);

  ED_treeview11_gestionparking = gtk_tree_view_new ();
  gtk_widget_show (ED_treeview11_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed5), ED_treeview11_gestionparking, 120, 96);
  gtk_widget_set_size_request (ED_treeview11_gestionparking, 624, 400);

  ED_label19_gestionparking = gtk_label_new (_("Affichage"));
  gtk_widget_show (ED_label19_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed5), ED_label19_gestionparking, 168, 24);
  gtk_widget_set_size_request (ED_label19_gestionparking, 144, 24);

  ED_label22_gestionparking = gtk_label_new (_("ParkingID :\n"));
  gtk_widget_show (ED_label22_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed5), ED_label22_gestionparking, 80, 56);
  gtk_widget_set_size_request (ED_label22_gestionparking, 112, 24);

  ED_entry2_AFFgestionparking = gtk_entry_new ();
  gtk_widget_show (ED_entry2_AFFgestionparking);
  gtk_fixed_put (GTK_FIXED (fixed5), ED_entry2_AFFgestionparking, 192, 48);
  gtk_widget_set_size_request (ED_entry2_AFFgestionparking, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (ED_entry2_AFFgestionparking), 8226);

  ED_button2_gestionparking = gtk_button_new ();
  gtk_widget_show (ED_button2_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed5), ED_button2_gestionparking, 264, 496);
  gtk_widget_set_size_request (ED_button2_gestionparking, 96, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (ED_button2_gestionparking), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image11 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox10), image11, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Retourner"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox10), label25, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) ED_treeview11_gestionparking, "row_activated",
                    G_CALLBACK (on_ED_treeview11_gestionparking_row_activated),
                    NULL);
  g_signal_connect ((gpointer) ED_entry2_AFFgestionparking, "changed",
                    G_CALLBACK (on_ED_entry2_AFFgestionparking_changed),
                    NULL);
  g_signal_connect ((gpointer) ED_button2_gestionparking, "clicked",
                    G_CALLBACK (on_ED_button2_gestionparking_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Affich, Affich, "Affich");
  GLADE_HOOKUP_OBJECT (Affich, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Affich, ED_treeview11_gestionparking, "ED_treeview11_gestionparking");
  GLADE_HOOKUP_OBJECT (Affich, ED_label19_gestionparking, "ED_label19_gestionparking");
  GLADE_HOOKUP_OBJECT (Affich, ED_label22_gestionparking, "ED_label22_gestionparking");
  GLADE_HOOKUP_OBJECT (Affich, ED_entry2_AFFgestionparking, "ED_entry2_AFFgestionparking");
  GLADE_HOOKUP_OBJECT (Affich, ED_button2_gestionparking, "ED_button2_gestionparking");
  GLADE_HOOKUP_OBJECT (Affich, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (Affich, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (Affich, image11, "image11");
  GLADE_HOOKUP_OBJECT (Affich, label25, "label25");

  return Affich;
}

GtkWidget*
create_Affec_agent (void)
{
  GtkWidget *Affec_agent;
  GtkWidget *fixed6;
  GtkWidget *ED_label20_gestionparking;
  GtkWidget *aa_entry1_ag;
  GtkWidget *ED_label888_gestionparking;
  GtkWidget *ED_label21_gestionparking;
  GtkWidget *aa_entry_ag;
  GtkWidget *ED_button12_gestionparking;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image9;
  GtkWidget *label18;
  GtkWidget *button1_gestionparking;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image8;
  GtkWidget *label17;
  GtkWidget *aa_label_ag;
  GtkWidget *aaaaah;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image18;
  GtkWidget *label32;

  Affec_agent = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Affec_agent), _("Affectation agents"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (Affec_agent), fixed6);

  ED_label20_gestionparking = gtk_label_new (_("Affectation des agents"));
  gtk_widget_show (ED_label20_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed6), ED_label20_gestionparking, 128, 16);
  gtk_widget_set_size_request (ED_label20_gestionparking, 176, 32);

  aa_entry1_ag = gtk_entry_new ();
  gtk_widget_show (aa_entry1_ag);
  gtk_fixed_put (GTK_FIXED (fixed6), aa_entry1_ag, 152, 64);
  gtk_widget_set_size_request (aa_entry1_ag, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (aa_entry1_ag), 8226);

  ED_label888_gestionparking = gtk_label_new (_("Agent ID :"));
  gtk_widget_show (ED_label888_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed6), ED_label888_gestionparking, 32, 112);
  gtk_widget_set_size_request (ED_label888_gestionparking, 100, 24);

  ED_label21_gestionparking = gtk_label_new (_("Parking ID :"));
  gtk_widget_show (ED_label21_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed6), ED_label21_gestionparking, 0, 64);
  gtk_widget_set_size_request (ED_label21_gestionparking, 184, 24);

  aa_entry_ag = gtk_entry_new ();
  gtk_widget_show (aa_entry_ag);
  gtk_fixed_put (GTK_FIXED (fixed6), aa_entry_ag, 152, 104);
  gtk_widget_set_size_request (aa_entry_ag, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (aa_entry_ag), 8226);

  ED_button12_gestionparking = gtk_button_new ();
  gtk_widget_show (ED_button12_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed6), ED_button12_gestionparking, 296, 400);
  gtk_widget_set_size_request (ED_button12_gestionparking, 106, 32);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (ED_button12_gestionparking), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image9 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox8), image9, FALSE, FALSE, 0);

  label18 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label18);
  gtk_box_pack_start (GTK_BOX (hbox8), label18, FALSE, FALSE, 0);

  button1_gestionparking = gtk_button_new ();
  gtk_widget_show (button1_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed6), button1_gestionparking, 120, 400);
  gtk_widget_set_size_request (button1_gestionparking, 106, 32);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button1_gestionparking), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image8 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox7), image8, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Confirmer"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox7), label17, FALSE, FALSE, 0);

  aa_label_ag = gtk_label_new ("");
  gtk_widget_show (aa_label_ag);
  gtk_fixed_put (GTK_FIXED (fixed6), aa_label_ag, 24, 240);
  gtk_widget_set_size_request (aa_label_ag, 440, 128);

  aaaaah = gtk_button_new ();
  gtk_widget_show (aaaaah);
  gtk_fixed_put (GTK_FIXED (fixed6), aaaaah, 320, 168);
  gtk_widget_set_size_request (aaaaah, 106, 32);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (aaaaah), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image18 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox17), image18, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Rechercher"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox17), label32, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) ED_button12_gestionparking, "clicked",
                    G_CALLBACK (on_ED_button12_gestionparking_clicked),
                    NULL);
  g_signal_connect ((gpointer) button1_gestionparking, "clicked",
                    G_CALLBACK (on_button1_gestionparking_clicked),
                    NULL);
  g_signal_connect ((gpointer) aaaaah, "clicked",
                    G_CALLBACK (on_aaaaah_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Affec_agent, Affec_agent, "Affec_agent");
  GLADE_HOOKUP_OBJECT (Affec_agent, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (Affec_agent, ED_label20_gestionparking, "ED_label20_gestionparking");
  GLADE_HOOKUP_OBJECT (Affec_agent, aa_entry1_ag, "aa_entry1_ag");
  GLADE_HOOKUP_OBJECT (Affec_agent, ED_label888_gestionparking, "ED_label888_gestionparking");
  GLADE_HOOKUP_OBJECT (Affec_agent, ED_label21_gestionparking, "ED_label21_gestionparking");
  GLADE_HOOKUP_OBJECT (Affec_agent, aa_entry_ag, "aa_entry_ag");
  GLADE_HOOKUP_OBJECT (Affec_agent, ED_button12_gestionparking, "ED_button12_gestionparking");
  GLADE_HOOKUP_OBJECT (Affec_agent, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Affec_agent, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Affec_agent, image9, "image9");
  GLADE_HOOKUP_OBJECT (Affec_agent, label18, "label18");
  GLADE_HOOKUP_OBJECT (Affec_agent, button1_gestionparking, "button1_gestionparking");
  GLADE_HOOKUP_OBJECT (Affec_agent, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Affec_agent, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Affec_agent, image8, "image8");
  GLADE_HOOKUP_OBJECT (Affec_agent, label17, "label17");
  GLADE_HOOKUP_OBJECT (Affec_agent, aa_label_ag, "aa_label_ag");
  GLADE_HOOKUP_OBJECT (Affec_agent, aaaaah, "aaaaah");
  GLADE_HOOKUP_OBJECT (Affec_agent, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (Affec_agent, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (Affec_agent, image18, "image18");
  GLADE_HOOKUP_OBJECT (Affec_agent, label32, "label32");

  return Affec_agent;
}

GtkWidget*
create_CONFIR_supp (void)
{
  GtkWidget *CONFIR_supp;
  GtkWidget *fixed7;
  GtkWidget *ED_image1_gestionparking;
  GtkWidget *ED_label7_gestionparking;
  GtkWidget *ED_button200_gestionparking;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *label9;
  GtkWidget *ED_button100_gestionparking;
  GtkWidget *ED_alignment1_gestionparking;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *label8;

  CONFIR_supp = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (CONFIR_supp), _("Confirmation de suppression"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (CONFIR_supp), fixed7);

  ED_image1_gestionparking = gtk_image_new_from_stock ("gtk-caps-lock-warning", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (ED_image1_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed7), ED_image1_gestionparking, 32, 72);
  gtk_widget_set_size_request (ED_image1_gestionparking, 56, 64);

  ED_label7_gestionparking = gtk_label_new (_("VOus etes sur de supprimer ce parking ?\n\nCette action est irreversible!!!!!"));
  gtk_widget_show (ED_label7_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed7), ED_label7_gestionparking, 88, 32);
  gtk_widget_set_size_request (ED_label7_gestionparking, 304, 144);

  ED_button200_gestionparking = gtk_button_new ();
  gtk_widget_show (ED_button200_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed7), ED_button200_gestionparking, 192, 200);
  gtk_widget_set_size_request (ED_button200_gestionparking, 160, 48);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (ED_button200_gestionparking), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-cancel", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox2), label9, FALSE, FALSE, 0);

  ED_button100_gestionparking = gtk_button_new ();
  gtk_widget_show (ED_button100_gestionparking);
  gtk_fixed_put (GTK_FIXED (fixed7), ED_button100_gestionparking, 56, 200);
  gtk_widget_set_size_request (ED_button100_gestionparking, 128, 48);

  ED_alignment1_gestionparking = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (ED_alignment1_gestionparking);
  gtk_container_add (GTK_CONTAINER (ED_button100_gestionparking), ED_alignment1_gestionparking);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (ED_alignment1_gestionparking), hbox1);

  image2 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox1), label8, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) ED_button200_gestionparking, "clicked",
                    G_CALLBACK (on_ED_button200_gestionparking_clicked),
                    NULL);
  g_signal_connect ((gpointer) ED_button100_gestionparking, "clicked",
                    G_CALLBACK (on_ED_button100_gestionparking_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (CONFIR_supp, CONFIR_supp, "CONFIR_supp");
  GLADE_HOOKUP_OBJECT (CONFIR_supp, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (CONFIR_supp, ED_image1_gestionparking, "ED_image1_gestionparking");
  GLADE_HOOKUP_OBJECT (CONFIR_supp, ED_label7_gestionparking, "ED_label7_gestionparking");
  GLADE_HOOKUP_OBJECT (CONFIR_supp, ED_button200_gestionparking, "ED_button200_gestionparking");
  GLADE_HOOKUP_OBJECT (CONFIR_supp, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (CONFIR_supp, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (CONFIR_supp, image3, "image3");
  GLADE_HOOKUP_OBJECT (CONFIR_supp, label9, "label9");
  GLADE_HOOKUP_OBJECT (CONFIR_supp, ED_button100_gestionparking, "ED_button100_gestionparking");
  GLADE_HOOKUP_OBJECT (CONFIR_supp, ED_alignment1_gestionparking, "ED_alignment1_gestionparking");
  GLADE_HOOKUP_OBJECT (CONFIR_supp, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (CONFIR_supp, image2, "image2");
  GLADE_HOOKUP_OBJECT (CONFIR_supp, label8, "label8");

  return CONFIR_supp;
}

