/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Layout (void);
GtkWidget* create_Supp (void);
GtkWidget* create_ADD_MOD (void);
GtkWidget* create_Affich (void);
GtkWidget* create_Affec_agent (void);
GtkWidget* create_CONFIR_supp (void);
