/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Layout;
  GtkWidget *Supp;
  GtkWidget *ADD_MOD;
  GtkWidget *Affich;
  GtkWidget *Affec_agent;
  GtkWidget *CONFIR_de_supp;
  GtkWidget *Msg_erreur;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Layout = create_Layout ();
  gtk_widget_show (Layout);
 /* Supp = create_Supp ();
  gtk_widget_show (Supp);
  ADD_MOD = create_ADD_MOD ();
  gtk_widget_show (ADD_MOD);
  Affich = create_Affich ();
  gtk_widget_show (Affich);
  Affec_agent = create_Affec_agent ();
  gtk_widget_show (Affec_agent);
  CONFIR_de_supp = create_CONFIR_de_supp ();
  gtk_widget_show (CONFIR_de_supp);
  Msg_erreur = create_Msg_erreur ();
  gtk_widget_show (Msg_erreur);*/
	

  gtk_main ();
  return 0;
}

